### ISSUE TITLE
Test broken

### ISSUE THREAD

**Issue by thuyanduong-flatiron** [learn-co-curriculum/fewpjs-js-fundamentals-variables-lab#4]
the code
```
const companyName = 'Scuber'
```
does not pass the test case
```
companyName 1) raises error if the companyName is changed
```

even though it should...

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced!
If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by RylanBauermeister** [comment]
This should still be open, and it should be expanded.  I made a new issue in the meanwhile: https://github.com/learn-co-curriculum/fewpjs-js-fundamentals-variables-lab/issues/5
