### ISSUE TITLE
Tests Fail Under Correct, Succeed Under Incorrect Circumstances 

### ISSUE THREAD

**Issue by RylanBauermeister** [learn-co-curriculum/fewpjs-js-fundamentals-variables-lab#5]
The tests currently try to test for companyName being a const, and the other two variables being lets.  It fails at all three instances.

**Behavior**:
For the following code:
```
const companyName = "Scuber";
const mostProfitableNeighborhood = "Chelsea";
const companyCeo = "Susan Smith";
```
All tests pass except the one checking if companyName is a const, which fails due to the use of an undeclared variable in the test (ReferenceError: js is not defined).  

**Expected**:
Later tests checking for let declaration should fail by raising typeError.  First test should pass by raising typeError.

**Comment by drakeltheryuujin** [comment]
Hi @RylanBauermeister,

The first test will not pass by raising typeError as demonstrated in issue #4. The compiler converts `const` to `let` and it will fail every time. The variables were missing from the top of the file and have been added so that the test will pass.

Thanks!
